### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Birdulon** [ErikReider/SwayNotificationCenter#14]
Ubuntu 21.04
libjson-glib-dev/hirsute,now 1.6.2-1 amd64
libgtk-layer-shell-dev/hirsute 0.5.2-1 amd64

```-:~/code/wayland/SwayNotificationCenter$ meson build
The Meson build system
Version: 0.59.1
Source dir: /home/luke/code/wayland/SwayNotificationCenter
Build dir: /home/luke/code/wayland/SwayNotificationCenter/build
Build type: native build
Project name: sway-notificaton-center
Project version: 0.1.0
C compiler for the host machine: cc (gcc 10.3.0 "cc (Ubuntu 10.3.0-1ubuntu1) 10.3.0")
C linker for the host machine: cc ld.bfd 2.36.1
Vala compiler for the host machine: valac (valac 0.48.17)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gio-2.0 found: YES 2.68.1
Run-time dependency gtk+-3.0 found: YES 3.24.25
Run-time dependency json-glib-1.0 found: YES 1.6.2
Library gtk-layer-shell found: YES
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Build targets in project: 4

Found ninja-1.10.1 at /usr/bin/ninja
-:~/code/wayland/SwayNotificationCenter$ ninja -C build/
ninja: Entering directory `build/'
[5/18] Compiling Vala source ../src/main.vala ../src/notiDaemon/n...Action/topAction.vala ../src/constants.vala ../src/functions.vala
FAILED: src/swaync.p/main.c src/swaync.p/notiDaemon/notiDaemon.c src/swaync.p/configModel/configModel.c src/swaync.p/notiWindow/notiWindow.c src/swaync.p/notification/notification.c src/swaync.p/controlCenter/controlCenter.c src/swaync.p/controlCenter/topAction/topAction.c src/swaync.p/constants.c src/swaync.p/functions.c 
valac -C --debug --debug --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg gio-2.0 --color=always --directory src/swaync.p --basedir ../src --gresources=../src/sway_notificaton_center.gresource.xml --target-glib=2.50 --pkg=GtkLayerShell-0.1 ../src/main.vala ../src/notiDaemon/notiDaemon.vala ../src/configModel/configModel.vala ../src/notiWindow/notiWindow.vala ../src/notification/notification.vala ../src/controlCenter/controlCenter.vala ../src/controlCenter/topAction/topAction.vala ../src/constants.vala ../src/functions.vala
../src/controlCenter/controlCenter.vala:97.13-97.43: error: The name `set_keyboard_mode' does not exist in the context of `GtkLayerShell' (gtk-layer-shell-0)
            GtkLayerShell.set_keyboard_mode (this, GtkLayerShell.KeyboardMode.ON_DEMAND);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
[7/18] Compiling C object src/swaync-client.p/meson-generated_client.c.o
ninja: build stopped: subcommand failed.
```

Potentially related to https://github.com/wmww/gtk-layer-shell/commit/9cd93e9f51702e50e5b943650fb612f16f94a648 
Perhaps there should be a minimum version defined for gtk-layer-shell of 0.6.0 to cover this?

**Comment by ErikReider** [comment]
What version of gtk-layer-shell do you have installed?

**Comment by Birdulon** [comment]
libgtk-layer-shell0/hirsute,now 0.5.2-1 amd64

First release after that API change seems to be v0.6.0

**Comment by ErikReider** [comment]
So the library requires v0.6.0. What's the latest version in Ubuntus repos?

**Comment by Birdulon** [comment]
v0.5.2-2
I had no issues building it from source but I have no idea what other concerns there might be for the distro package maintainers.

**Comment by ErikReider** [comment]
03a68bff88166a5c27675e10d537efafda7724c0 should fix this :)

**Comment by Birdulon** [comment]
Not sure if I messed something up deleting my v0.6.0 .so files but it seems to keep trying to link against the minor_version>6 path and failing. I've confirmed that the else branch works correctly on v0.5.2 by commenting out the if block where appropriate.

I've confirmed that the function gives the expected result at runtime by adding `print ("GTK version %u.%u.%u\n", GtkLayerShell.get_major_version (), GtkLayerShell.get_minor_version (), GtkLayerShell.get_micro_version ());
    }` elsewhere and getting `GTK version 0.5.2`, so it might be an issue of the check being runtime and the linker not liking that.

```
:~/code/wayland/SwayNotificationCenter$ ninja -C build
ninja: Entering directory `build'
[5/18] Compiling Vala source ../src/main.vala ../src/notiDaemon/n...Action/topAction.vala ../src/constants.vala ../src/functions.vala
FAILED: src/swaync.p/main.c src/swaync.p/notiDaemon/notiDaemon.c src/swaync.p/configModel/configModel.c src/swaync.p/notiWindow/notiWindow.c src/swaync.p/notification/notification.c src/swaync.p/controlCenter/controlCenter.c src/swaync.p/controlCenter/topAction/topAction.c src/swaync.p/constants.c src/swaync.p/functions.c 
valac -C --debug --debug --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg gio-2.0 --color=always --directory src/swaync.p --basedir ../src --gresources=../src/sway_notificaton_center.gresource.xml --target-glib=2.50 --pkg=GtkLayerShell-0.1 ../src/main.vala ../src/notiDaemon/notiDaemon.vala ../src/configModel/configModel.vala ../src/notiWindow/notiWindow.vala ../src/notification/notification.vala ../src/controlCenter/controlCenter.vala ../src/controlCenter/topAction/topAction.vala ../src/constants.vala ../src/functions.vala
../src/controlCenter/controlCenter.vala:100.17-100.56: warning: `GtkLayerShell.set_keyboard_interactivity' has been deprecated since 0.6
../src/main.vala:54.42-54.75: error: Argument 2: Cannot convert from `uint' to `int'
        print ("GTK version %d.%d.%d\n", GtkLayerShell.get_major_version (), GtkLayerShell.get_minor_version (), GtkLayerShell.get_micro_version ());
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 1 warning(s)
[7/18] Compiling C object src/swaync-client.p/meson-generated_client.c.o
ninja: build stopped: subcommand failed.
```

**Comment by ErikReider** [comment]
Try this branch #15

**Comment by Birdulon** [comment]
Sorry for late reply, tested just now and it builds perfectly, thank you :)

Aside: had some fun with meson running the pre-processor on remnants of my 0.6.0 build but then linking against the system 0.5.2 gtk-layer-shell library, had to search and destroy on my system to fix that up. I've verified that with my system in a cleaner state, 03a68bf still produced the same linking error so #15 was still necessary. Thanks again!
